app = "moneybags"
primary_region = "iad"

[build]
  # Use Dockerfile by default

[http_service]
  internal_port = 8080
  force_https = true

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
